import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, MessageCircle } from "lucide-react";
import { email, phoneDisplay, whatsapp } from "./data";
import { CookiePreferencesButton } from "./consent-analytics";

export function Header(){return <header className="site-header"><Link href="/" className="brand" aria-label="Marca WebSites — página inicial"><Image src="/marca-websites-logo.webp" width={210} height={76} alt="" priority/></Link><nav aria-label="Navegação principal"><Link href="/#projetos">Projetos</Link><Link href="/#servicos">Serviços</Link><Link href="/#sobre">Sobre</Link></nav><a className="header-cta" href={whatsapp} target="_blank" rel="noreferrer"><span className="header-cta-full">Vamos conversar</span><span className="header-cta-short">WhatsApp</span> <ArrowUpRight size={16}/></a></header>}

export function BrowserPreview({url,title,mobile=false,image}:{url:string,title:string,mobile?:boolean,image?:string}){return <figure className={`browser-frame ${mobile?"mobile-frame":""}`}><div className="browser-bar" aria-hidden="true"><i/><i/><i/><span>{url.replace("https://","").replace(/\/$/,"")}</span></div>{image?<div className="site-capture"><Image src={image} fill sizes={mobile?"(max-width: 520px) 88vw, 390px":"(max-width: 850px) 90vw, 58vw"} alt={`Página inicial do site ${title}`}/></div>:<div className="preview-fallback"><span>{title}</span><small>Projeto comercial</small></div>}</figure>}

export function Footer(){return <><section className="final-cta" id="contato" aria-labelledby="titulo-contato"><p className="eyebrow">Tem um projeto em mente?</p><h2 id="titulo-contato">Sua empresa precisa de um site profissional?</h2><p>Conte o que você precisa e vamos avaliar o melhor caminho para o projeto.</p><a className="button orange" href={whatsapp} target="_blank" rel="noreferrer">Falar pelo WhatsApp <ArrowUpRight size={19}/></a></section><footer><div className="footer-brand"><Image src="/marca-websites-logo.webp" width={220} height={82} alt="Marca WebSites"/><small>© 2026 Marca WebSites</small></div><div><p>Marcio Cabral — Web Designer Freelancer</p><a href="tel:+5588996777332">WhatsApp: {phoneDisplay}</a><a href={`mailto:${email}`}>{email}</a><span>Atendimento remoto · Base em Tianguá, CE</span></div><div className="footer-links"><Link href="/#projetos">Projetos</Link><Link href="/#servicos">Serviços</Link><Link href="/privacidade">Privacidade</Link><Link href="/termos">Termos de uso</Link><CookiePreferencesButton/></div></footer><a className="mobile-whatsapp" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Conversar com Marcio Cabral pelo WhatsApp"><MessageCircle size={20} aria-hidden="true"/> WhatsApp</a></>}
