export const whatsapp = "https://wa.me/5588996777332?text=Ol%C3%A1%2C%20Marcio!%20Vi%20o%20site%20da%20Marca%20WebSites%20e%20gostaria%20de%20conversar%20sobre%20a%20cria%C3%A7%C3%A3o%20de%20um%20site%20para%20minha%20empresa.";
export const siteUrl = "https://marcaweb.site";
export const email = "marciocabralpro@gmail.com";
export const phoneDisplay = "(88) 99677-7332";

export const projects = [
  { slug:"ravyt-digital", title:"Ravyt Digital", category:"Site Institucional / Marketing Digital", url:"https://ravytdigital.com/", color:"blue", short:"Uma presença digital construída para apresentar especialização, serviços e caminhos de contato com clareza.", description:"Site institucional desenvolvido para uma empresa especializada em gestão de redes sociais para psicólogas parentais, com foco em posicionamento, serviços e geração de contatos.", challenge:"Organizar uma oferta especializada e transformar a experiência da agência em uma apresentação clara, confiável e capaz de conduzir o visitante ao diagnóstico e ao contato.", solution:"Criamos uma estrutura editorial que conecta posicionamento, serviços e conversão. A navegação foi reduzida ao essencial, com hierarquia forte e chamadas para ação distribuídas ao longo da jornada.", decisions:["Mensagem principal direta para o público da agência","Serviços organizados por nível de necessidade","Conteúdo e contexto próximos aos CTAs","Experiência responsiva priorizando leitura no celular"] },
  { slug:"cerest-tiangua", title:"CEREST Tianguá", category:"Site Institucional / Saúde do Trabalhador", url:"https://site-cerest-tiangua.ravytdigital.workers.dev/", color:"green", short:"Informação pública organizada para orientar, acolher e facilitar o acesso aos serviços.", description:"Projeto institucional estruturado para organizar informações sobre saúde do trabalhador, áreas de atuação, materiais educativos, atendimento e canais de contato.", challenge:"Reunir um volume amplo de informações institucionais e educativas sem tornar a experiência burocrática, ajudando trabalhadores e profissionais a encontrarem rapidamente o conteúdo necessário.", solution:"Estruturamos o conteúdo por intenção de acesso, equilibrando informação pública, materiais educativos e canais de atendimento em uma navegação simples e acessível.", decisions:["Arquitetura orientada às dúvidas do usuário","Conteúdo institucional com linguagem acessível","Destaque para atendimento e materiais educativos","Responsividade e contraste como prioridades"] },
  { slug:"capoeira-haute-savoie", title:"Capoeira Haute-Savoie", category:"Site Institucional / Organização esportiva internacional", url:"https://site-capoeira-haute-savoie.ravytdigital.workers.dev/", color:"yellow", short:"Cultura, movimento e comunidade apresentados em uma experiência bilíngue e vibrante.", description:"Site desenvolvido para uma organização de Capoeira na França, reunindo apresentação institucional, aulas, cidades atendidas, eventos, história e contato.", challenge:"Apresentar a capoeira como prática cultural, esportiva e comunitária para um público internacional, organizando aulas, locais, eventos e história sem perder a energia do grupo.", solution:"Criamos uma experiência visual dinâmica, com navegação clara entre cidades, atividades e conteúdos institucionais, respeitando a identidade cultural da organização.", decisions:["Direção visual inspirada nas cores do grupo","Conteúdo organizado por cidade e atividade","Equilíbrio entre história, aulas e eventos","Interface preparada para público internacional"] },
] as const;

export const concepts = [
  {title:"Construpiso Home Center",url:"https://site-construpiso.ravytdigital.workers.dev/",tone:"orange",description:"Conceito de site comercial para apresentar departamentos, produtos e facilitar o contato com a loja."},
  {title:"J Frios Distribuidor",url:"https://site-jfrios.ravytdigital.workers.dev/",tone:"red",description:"Proposta digital para uma distribuidora, com foco em portfólio, atendimento e oportunidades comerciais."}
] as const;
